name: Deploy Docker image on EC2 instances

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Set version tag
        run: echo "TAG=v${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build & Push to Docker Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            aniketjok/fashion:${{ env.TAG }}
            aniketjok/fashion:latest

  Deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy on EC2 instances.
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:  ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSHKEY }}
          script: |
            docker pull aniketjok/fashion:latest
            docker stop fashion || true
            docker rm fashion || true
            docker run -d -p 80:80 --name fashion aniketjok/fashion:latest          
          
